"""Legal body copy for locales added after the original five-language launch."""

ADDITIONAL = {
    "de": {
        "privacy": """<h1>Datenschutzerklärung</h1><p class="lede">Yido Kids ist eine App für familiäre Gewohnheiten. Aufgaben, Check-ins, Fortschritt, Belohnungen, Fotos und Aufnahmen bleiben standardmäßig auf dem Gerät. Wir verkaufen keine personenbezogenen Daten und verwenden weder zielgerichtete Werbung noch Analyse-SDKs Dritter in der Kids-Version.</p><h2>Welche Informationen verarbeitet werden</h2><p>Eltern können auf dem Gerät Profile mit Spitznamen und Bildern, Aufgaben, Check-ins, Bewertungen, Belohnungen, Erinnerungen, Fotos und Sprachaufnahmen anlegen. Diese Angaben dienen den von der Familie gewählten Funktionen. Bitte tragen Sie keine unnötigen Angaben zur Identität eines Kindes ein.</p><h2>Speicherung und Weitergabe</h2><p>Die Daten liegen in der lokalen Datenbank und im Dokumentenspeicher der App. Betriebssystem-Backups können sie je nach Geräteeinstellung enthalten. Nur wenn ein Elternteil eine Datei exportiert oder Inhalte über die Systemfunktion teilt, werden die gewählten Inhalte an den gewählten Dienst übergeben. </p><h2>Berechtigungen und Käufe</h2><p>Kamera und Fotos werden für Profilbilder oder optionale Fotobestätigungen genutzt, das Mikrofon für von Eltern aufgenommene Sprachhinweise und Benachrichtigungen für lokale Erinnerungen. Biometrie kann die Elternfreigabe entsperren, falls aktiviert. Apple oder Google verarbeitet Käufe; wir erhalten keine vollständigen Kartendaten.</p><h2>Rechte, Aufbewahrung und Änderungen</h2><p>Eltern können Inhalte in der App bearbeiten oder löschen. Eine Deinstallation entfernt lokale App-Daten; System-Backups verwalten Sie in den Geräteeinstellungen. Für Auskunft, Berichtigung oder Löschung wenden Sie sich bitte über die private E-Mail-Adresse unten an uns. Bei wesentlichen Änderungen aktualisieren wir dieses Dokument und sein Datum.</p>""",
        "terms": """<h1>Nutzungsbedingungen</h1><p class="lede">Bitte lesen Sie diese Bedingungen als Elternteil oder Sorgeberechtigte, bevor Ihre Familie Yido nutzt.</p><h2>Die App</h2><p>Yido unterstützt Familien bei Aufgaben, Gewohnheiten, Erinnerungen und Belohnungen. Es ist weder medizinische Versorgung noch anerkannter Unterricht oder Kinderbetreuung. Erwachsene richten die Nutzung durch Kinder ein und beaufsichtigen sie angemessen.</p><h2>Inhalte und Gerät</h2><p>Die Familie fügt Aufgaben, Fotos, Profilbilder und Aufnahmen selbst hinzu. Verwenden Sie nur geeignete Inhalte, zu deren Nutzung Sie berechtigt sind. Schützen Sie das Gerät, die Eltern-PIN, das Store-Konto und exportierte Dateien.</p><h2>Käufe und Abonnements</h2><p>Wenn kostenpflichtige Funktionen angeboten werden, zeigt die Kaufansicht den tatsächlichen Preis, die Laufzeit und die Verlängerungsbedingungen. Apple oder Google verarbeitet Kauf, Verlängerung, Erstattung und Kündigung nach den Regeln des jeweiligen Stores. Abonnements können im entsprechenden Store-Konto verwaltet oder gekündigt werden.</p><h2>Verfügbarkeit und Änderungen</h2><p>Wir bemühen uns um eine zuverlässige App, können aber keine fehlerfreie oder ununterbrochene Nutzung garantieren. Daten können etwa durch Geräteverlust oder fehlende Backups verloren gehen. Gesetzliche Verbraucherrechte bleiben unberührt. Bei Änderungen der App oder der Anforderungen aktualisieren wir diese Bedingungen und das angezeigte Datum.</p>""",
        "children": """<h1>Datenschutz für Kinder</h1><p class="lede">Yido ist für die Nutzung durch Kinder unter Einrichtung und Aufsicht eines Elternteils oder einer sorgeberechtigten Person gedacht. Wir beschränken die Verarbeitung auf das Nötige und speichern Familieninhalte standardmäßig lokal.</p><h2>Mitwirkung der Eltern</h2><p>Erwachsene sollten die Datenschutzhinweise lesen und Profile, Aufgaben, Erinnerungen, optionale Fotos und Sprachaufnahmen sowie Käufe einrichten. Sensible Einstellungen und Dateiübertragungen sind Sache der Eltern.</p><h2>Informationen und Schutz</h2><p>Auf dem Gerät können Spitznamen, Bilder, Aufgaben, Check-ins, Bewertungen, Belohnungen, Fotos und Stimmen gespeichert werden. Yido Kids verlangt kein öffentliches Kinderkonto, bietet keinen öffentlichen Feed oder Chat mit Fremden und erstellt keine Werbeprofile aus Kinderdaten. Die Kids-Version nutzt keine Analyse-SDKs Dritter.</p><h2>Rechte der Eltern und Dritte</h2><p>Eltern können lokale Inhalte ansehen, ändern oder löschen. Die Deinstallation entfernt lokale App-Daten; Backups werden in den Systemeinstellungen verwaltet. Apple oder Google verarbeitet Store-Käufe. Nur bei einer bewussten Freigabe oder einem Export durch Eltern gelangen ausgewählte Inhalte an einen von ihnen gewählten Dienst. Für weitere Fragen schreiben Sie an die private E-Mail-Adresse unten.</p>""",
    },
    "es": {
        "privacy": """<h1>Política de privacidad</h1><p class="lede">Yido Kids es una aplicación de hábitos para familias. Las tareas, registros, avances, recompensas, fotos y grabaciones permanecen en el dispositivo de forma predeterminada. No vendemos datos personales ni usamos publicidad personalizada o SDK de análisis de terceros en la versión Kids.</p><h2>Información que tratamos</h2><p>Los padres pueden crear en el dispositivo perfiles con apodos e imágenes, tareas, registros, puntuaciones, recompensas, recordatorios, fotos y grabaciones de voz. Se utilizan para las funciones elegidas por la familia. Evita incluir datos de identidad del menor que no sean necesarios.</p><h2>Almacenamiento y comunicación</h2><p>Los datos se guardan en la base de datos y los documentos locales de la aplicación. Las copias del sistema operativo pueden incluirlos según la configuración del dispositivo. Solo cuando un adulto exporta un archivo o comparte contenido mediante el sistema, el contenido elegido se entrega al servicio que haya seleccionado. </p><h2>Permisos y compras</h2><p>La cámara y las fotos sirven para imágenes de perfil o comprobaciones opcionales; el micrófono, para indicaciones de voz grabadas por los padres; y las notificaciones, para recordatorios locales. La biometría puede desbloquear el acceso parental si se activa. Apple o Google tramita las compras; no recibimos los datos completos de la tarjeta.</p><h2>Opciones, conservación y cambios</h2><p>Los padres pueden editar o borrar contenido en la aplicación. Al desinstalarla se eliminan los datos locales; las copias del sistema se gestionan en sus ajustes. Para consultas, rectificación o eliminación, usa el correo privado indicado abajo. Si hay cambios importantes, actualizaremos esta política y su fecha.</p>""",
        "terms": """<h1>Condiciones de uso</h1><p class="lede">Un padre, madre o tutor debe leer estas condiciones antes de que la familia utilice Yido.</p><h2>La aplicación</h2><p>Yido ayuda a las familias a organizar tareas, hábitos, recordatorios y recompensas. No presta asistencia sanitaria, enseñanza acreditada ni servicios de cuidado infantil. Los adultos configuran y supervisan el uso por menores.</p><h2>Contenido y dispositivo</h2><p>La familia añade sus propias tareas, fotos, imágenes de perfil y grabaciones. Utiliza únicamente contenido adecuado y sobre el que tengas derechos. Protege el dispositivo, el PIN parental, la cuenta de la tienda y los archivos exportados.</p><h2>Compras y suscripciones</h2><p>Si se ofrecen funciones de pago, la pantalla de compra muestra el precio, el período y las condiciones de renovación vigentes. Apple o Google tramita compras, renovaciones, reembolsos y cancelaciones conforme a las reglas de su tienda. Las suscripciones se gestionan o cancelan desde la cuenta de la tienda correspondiente.</p><h2>Disponibilidad y cambios</h2><p>Intentamos mantener la aplicación disponible, pero no podemos garantizar un funcionamiento ininterrumpido o sin errores. La pérdida del dispositivo o la falta de copias pueden causar pérdida de datos. Se mantienen los derechos de los consumidores reconocidos por la ley. Si cambian la aplicación o los requisitos, actualizaremos estas condiciones y su fecha.</p>""",
        "children": """<h1>Privacidad infantil</h1><p class="lede">Yido está pensado para menores bajo la configuración y supervisión de un padre, madre o tutor. Limitamos el tratamiento a lo necesario y guardamos el contenido familiar en el dispositivo por defecto.</p><h2>Participación de los padres</h2><p>Un adulto debe leer el aviso de privacidad y configurar perfiles, tareas, recordatorios, fotos o grabaciones opcionales y compras. Los ajustes sensibles y la transferencia de archivos corresponden a los padres.</p><h2>Información y protección</h2><p>En el dispositivo pueden guardarse apodos, imágenes, tareas, registros, puntuaciones, recompensas, fotos y voces. Yido Kids no exige una cuenta pública al menor, no ofrece un muro público ni chat con desconocidos y no crea perfiles publicitarios a partir de datos infantiles. La versión Kids no utiliza SDK de análisis de terceros.</p><h2>Derechos de los padres y terceros</h2><p>Los padres pueden consultar, cambiar o borrar el contenido local. La desinstalación elimina los datos locales; las copias se gestionan en los ajustes del sistema. Apple o Google tramita las compras. Solo cuando un adulto comparte o exporta deliberadamente contenido elegido se entrega al servicio que haya seleccionado. Para más ayuda, usa el correo privado indicado abajo.</p>""",
    },
    "fr": {
        "privacy": """<h1>Politique de confidentialité</h1><p class="lede">Yido Kids est une application d’habitudes familiales. Par défaut, tâches, pointages, progrès, récompenses, photos et enregistrements restent sur l’appareil. Nous ne vendons pas de données personnelles et la version Kids n’utilise ni publicité ciblée ni SDK d’analyse tiers.</p><h2>Informations traitées</h2><p>Les parents peuvent créer sur l’appareil des profils avec surnoms et images, tâches, pointages, notes, récompenses, rappels, photos et enregistrements vocaux. Ces données servent aux fonctions choisies par la famille. Évitez d’ajouter des informations d’identité inutiles concernant l’enfant.</p><h2>Stockage et partage</h2><p>Les données sont conservées dans la base locale et les documents de l’application. Les sauvegardes du système peuvent les inclure selon les réglages de l’appareil. Seul un export ou un partage volontaire par un parent transmet les éléments sélectionnés au service qu’il choisit. </p><h2>Autorisations et achats</h2><p>L’appareil photo et les photos servent aux images de profil ou aux validations facultatives ; le micro sert aux consignes vocales enregistrées par les parents ; les notifications servent aux rappels locaux. La biométrie peut déverrouiller l’accès parental si elle est activée. Apple ou Google traite les achats ; nous ne recevons pas les coordonnées complètes de la carte.</p><h2>Choix, conservation et mises à jour</h2><p>Les parents peuvent modifier ou supprimer les contenus dans l’application. La désinstallation efface les données locales ; les sauvegardes système se gèrent dans les réglages. Pour toute demande d’accès, de rectification ou de suppression, utilisez l’adresse e-mail privée ci-dessous. Nous mettrons à jour ce texte et sa date en cas de changement important.</p>""",
        "terms": """<h1>Conditions d’utilisation</h1><p class="lede">Un parent ou responsable légal doit lire ces conditions avant l’utilisation de Yido en famille.</p><h2>L’application</h2><p>Yido aide les familles à organiser tâches, habitudes, rappels et récompenses. Il ne fournit ni soins médicaux, ni enseignement diplômant, ni garde d’enfants. Les adultes configurent et supervisent l’utilisation par les enfants.</p><h2>Contenu et appareil</h2><p>La famille ajoute ses propres tâches, photos, images de profil et enregistrements. N’utilisez que des contenus adaptés et pour lesquels vous avez des droits. Protégez l’appareil, le code parental, le compte de la boutique et les fichiers exportés.</p><h2>Achats et abonnements</h2><p>Si des fonctions payantes sont proposées, l’écran d’achat affiche le prix, la durée et les conditions de renouvellement en vigueur. Apple ou Google gère achats, renouvellements, remboursements et résiliations selon les règles de sa boutique. Les abonnements se gèrent ou se résilient depuis le compte de la boutique concernée.</p><h2>Disponibilité et modifications</h2><p>Nous cherchons à maintenir l’application disponible, sans garantir un fonctionnement continu ou exempt d’erreurs. La perte d’un appareil ou l’absence de sauvegarde peut entraîner une perte de données. Les droits légaux des consommateurs restent applicables. Si le produit ou les exigences changent, nous mettrons à jour ces conditions et leur date.</p>""",
        "children": """<h1>Vie privée des enfants</h1><p class="lede">Yido est conçu pour les enfants sous la configuration et la supervision d’un parent ou responsable légal. Nous limitons le traitement au nécessaire et conservons par défaut les contenus familiaux sur l’appareil.</p><h2>Participation des parents</h2><p>Un adulte doit lire les informations de confidentialité et configurer profils, tâches, rappels, photos ou enregistrements facultatifs et achats. Les réglages sensibles et les transferts de fichiers relèvent des parents.</p><h2>Informations et protection</h2><p>Des surnoms, images, tâches, pointages, notes, récompenses, photos et voix peuvent être conservés sur l’appareil. Yido Kids n’exige pas de compte public pour l’enfant, n’offre ni fil public ni discussion avec des inconnus et ne crée pas de profil publicitaire à partir des données des enfants. La version Kids n’utilise pas de SDK d’analyse tiers.</p><h2>Droits des parents et tiers</h2><p>Les parents peuvent consulter, modifier ou supprimer les contenus locaux. La désinstallation efface les données locales ; les sauvegardes se gèrent dans les réglages du système. Apple ou Google traite les achats. Un partage ou export volontaire par un parent transmet uniquement les éléments choisis au service sélectionné. Pour toute aide, utilisez l’e-mail privé ci-dessous.</p>""",
    },
    "pt": {
        "privacy": """<h1>Política de privacidade</h1><p class="lede">O Yido Kids é uma aplicação de hábitos para famílias. Por predefinição, tarefas, registos, progresso, recompensas, fotografias e gravações ficam no dispositivo. Não vendemos dados pessoais e a versão Kids não usa publicidade direcionada nem SDKs de análise de terceiros.</p><h2>Dados tratados</h2><p>Os pais podem criar no dispositivo perfis com alcunhas e imagens, tarefas, registos, pontuações, recompensas, lembretes, fotografias e gravações de voz. Estes dados servem as funções escolhidas pela família. Evite inserir dados de identificação da criança que não sejam necessários.</p><h2>Armazenamento e partilha</h2><p>Os dados ficam na base de dados e nos documentos locais da aplicação. As cópias de segurança do sistema podem incluí-los, conforme as definições do dispositivo. Só quando um adulto exporta um ficheiro ou partilha conteúdos pelo sistema é que os elementos escolhidos são enviados ao serviço selecionado. </p><h2>Permissões e compras</h2><p>A câmara e as fotografias servem para imagens de perfil ou confirmações opcionais; o microfone, para instruções de voz gravadas pelos pais; e as notificações, para lembretes locais. A biometria pode desbloquear o acesso parental se estiver ativada. A Apple ou a Google trata das compras; não recebemos os dados completos do cartão.</p><h2>Escolhas, conservação e alterações</h2><p>Os pais podem editar ou apagar conteúdos na aplicação. A desinstalação remove dados locais; as cópias do sistema são geridas nas definições. Para acesso, correção ou eliminação, use o email privado abaixo. Em caso de alterações importantes, atualizaremos esta política e a respetiva data.</p>""",
        "terms": """<h1>Termos de utilização</h1><p class="lede">Um pai, mãe ou responsável deve ler estes termos antes de a família usar o Yido.</p><h2>A aplicação</h2><p>O Yido ajuda famílias a organizar tarefas, hábitos, lembretes e recompensas. Não presta cuidados médicos, ensino acreditado nem serviços de guarda de crianças. Os adultos configuram e acompanham o uso pelas crianças.</p><h2>Conteúdo e dispositivo</h2><p>A família adiciona as próprias tarefas, fotografias, imagens de perfil e gravações. Use apenas conteúdos adequados e para os quais tenha direitos. Proteja o dispositivo, o PIN parental, a conta da loja e os ficheiros exportados.</p><h2>Compras e subscrições</h2><p>Se forem oferecidas funcionalidades pagas, o ecrã de compra mostra o preço, o período e as condições de renovação em vigor. A Apple ou a Google trata de compras, renovações, reembolsos e cancelamentos segundo as regras da respetiva loja. As subscrições são geridas ou canceladas na conta da loja.</p><h2>Disponibilidade e alterações</h2><p>Procuramos manter a aplicação disponível, mas não garantimos funcionamento contínuo nem ausência de erros. A perda do dispositivo ou a falta de cópias de segurança pode causar perda de dados. Os direitos legais dos consumidores mantêm-se. Se o produto ou os requisitos mudarem, atualizaremos estes termos e a data.</p>""",
        "children": """<h1>Privacidade das crianças</h1><p class="lede">O Yido destina-se a crianças sob configuração e supervisão de um pai, mãe ou responsável. Limitamos o tratamento ao necessário e guardamos os conteúdos familiares no dispositivo por predefinição.</p><h2>Participação dos pais</h2><p>Um adulto deve ler o aviso de privacidade e configurar perfis, tarefas, lembretes, fotografias ou gravações opcionais e compras. As definições sensíveis e a transferência de ficheiros cabem aos pais.</p><h2>Dados e proteção</h2><p>O dispositivo pode guardar alcunhas, imagens, tarefas, registos, pontuações, recompensas, fotografias e vozes. O Yido Kids não exige uma conta pública para a criança, não oferece um feed público nem conversas com desconhecidos e não cria perfis publicitários com dados infantis. A versão Kids não usa SDKs de análise de terceiros.</p><h2>Direitos dos pais e terceiros</h2><p>Os pais podem consultar, alterar ou apagar os conteúdos locais. A desinstalação remove os dados locais; as cópias de segurança são geridas nas definições do sistema. A Apple ou a Google trata das compras. Só uma partilha ou exportação deliberada por um adulto envia os elementos escolhidos ao serviço selecionado. Para mais ajuda, use o email privado abaixo.</p>""",
    },
    "zh-Hant": {
        "privacy": """<h1>隱私權政策</h1><p class="lede">Yido Kids 是家庭習慣養成應用程式。任務、打卡、進度、獎勵、相片和錄音預設儲存在裝置上。我們不出售個人資料；Kids 版本不使用定向廣告或第三方分析 SDK。</p><h2>處理的資料</h2><p>家長可在裝置上建立含暱稱和圖片的個人檔案、任務、打卡、評分、獎勵、提醒、相片和語音錄音。這些資料用於家庭選用的功能。請避免填入不必要的兒童身分資料。</p><h2>儲存與分享</h2><p>資料儲存在應用程式的本機資料庫與文件中。作業系統備份可能依裝置設定包含應用程式資料。只有家長主動匯出檔案或透過系統分享時，所選內容才會交給家長選定的服務。</p><h2>權限與購買</h2><p>相機與相片用於個人檔案圖片或選用的拍照驗收；麥克風用於家長錄製的語音提示；通知用於本機提醒。若已啟用，生物辨識可用於家長解鎖。Apple 或 Google 處理購買；我們不取得完整的付款卡資料。</p><h2>家長選擇、保存與更新</h2><p>家長可在應用程式中編輯或刪除內容。解除安裝會刪除裝置上的資料；系統備份由家長在系統設定中管理。如需查詢、更正或刪除協助，請使用下方私人聯絡信箱。若有重大變更，我們會更新本政策及日期。</p>""",
        "terms": """<h1>使用條款</h1><p class="lede">請由家長或監護人在家庭使用 Yido 前閱讀本條款。</p><h2>應用程式服務</h2><p>Yido 協助家庭安排任務、習慣、提醒和獎勵，不提供醫療、具認證資格的教學或兒童托管服務。成年人負責設定並適當監督兒童的使用。</p><h2>家庭內容與裝置</h2><p>家庭自行新增任務、相片、個人檔案圖片和錄音。請只使用適合兒童且有權使用的內容，並妥善保護裝置、家長 PIN、商店帳戶及匯出檔案。</p><h2>購買與訂閱</h2><p>如提供付費功能，購買畫面會顯示當時的價格、週期和續訂條件。Apple 或 Google 依其商店規則處理購買、續訂、退款與取消。可在對應的商店帳戶中管理或取消訂閱。</p><h2>可用性與變更</h2><p>我們會合理維護應用程式，但無法保證服務永不中斷或完全沒有錯誤。裝置遺失或缺少備份可能造成資料損失；適用法律保障的消費者權利不受影響。產品或要求變更時，我們會更新條款及日期。</p>""",
        "children": """<h1>兒童個人資料保護</h1><p class="lede">Yido 供兒童在家長或監護人設定與監督下使用。我們盡量減少資料處理，家庭內容預設保存在裝置上。</p><h2>家長參與</h2><p>成年人應閱讀隱私提示，並設定個人檔案、任務、提醒、選用的相片與錄音及購買。敏感設定和檔案轉移應由家長處理。</p><h2>資料與保護</h2><p>裝置可能保存暱稱、圖片、任務、打卡、評分、獎勵、相片與語音。Yido Kids 不要求兒童註冊公開帳戶，不提供公開動態或與陌生人聊天，也不使用兒童資料建立廣告側寫。Kids 版本不使用第三方分析 SDK。</p><h2>家長權利與第三方</h2><p>家長可查看、修改或刪除本機內容。解除安裝會刪除裝置上的資料；系統備份在系統設定中管理。Apple 或 Google 處理商店購買。只有家長主動分享或匯出時，所選內容才會交給家長選定的服務。如需進一步協助，請使用下方私人聯絡信箱。</p>""",
    },
}

# Region variants share the same disclosures. Apply only phrase-level changes
# whose articles and agreement have been checked; blind word replacement can
# corrupt child-related or gendered legal wording.
ADDITIONAL["es-419"] = {
    key: value.replace("la aplicación", "la app").replace("La aplicación", "La app")
    .replace("esta aplicación", "esta app").replace("la cuenta de la tienda", "la cuenta de la tienda")
    for key, value in ADDITIONAL["es"].items()
}
ADDITIONAL["pt-BR"] = {
    key: value.replace("uma aplicação", "um aplicativo")
    .replace("A aplicação", "O aplicativo").replace("a aplicação", "o aplicativo")
    .replace("na aplicação", "no aplicativo").replace("da aplicação", "do aplicativo")
    .replace("as cópias de segurança", "os backups")
    .replace("As cópias de segurança", "Os backups")
    .replace("cópias de segurança", "backups")
    .replace("fotografias", "fotos").replace("ficheiros", "arquivos")
    .replace("ficheiro", "arquivo").replace("subscrições", "assinaturas")
    .replace("o ecrã", "a tela").replace("predefinição", "padrão")
    .replace("registos", "registros").replace("alcunhas", "apelidos")
    .replace("definições", "configurações").replace("câmara", "câmera")
    for key, value in ADDITIONAL["pt"].items()
}
