"""Reviewed UI and support copy for the Yido legal site.

The legal body sections in existing.json and ADDITIONAL below remain static HTML
so every language is readable even without JavaScript.
"""

UI = {
    "en": {
        "lang": "en", "label": "English", "nav": ["Privacy", "Terms", "Children's privacy", "Support"],
        "language_label": "Language",
        "home_title": "Good habits, with care", "home_lead": "Find Yido's privacy policy, terms, children's privacy information, and support in one place. Yido Kids keeps family activity on the device by default and does not use targeted ads or third-party analytics.",
        "cards": ["How Yido handles information and where it is stored.", "The terms for families using Yido.", "Parent controls and extra care for children's information.", "Help with the app, purchases, or privacy requests."],
        "support_intro": "For app help, purchases, privacy, or children’s data requests, contact Yido privately by email. Do not send a child’s photos or recordings unless we ask for them to resolve a specific request.",
        "support_private": "Private privacy and children's data requests", "support_public": "Product help",
        "support_data_heading": "Data and deletion", "support_store_heading": "Store purchases", "contact_heading": "Operator and contact",
        "support_tips": "Before reporting a problem, check app permissions and Yido's reminder and backup settings. Include the app version, device model, and steps to reproduce, but no child content.",
        "support_data": "Parents can edit or delete profiles, tasks, check-ins, photos, and recordings in the app. Uninstalling removes local app data; manage any OS backups in system settings. Email us if you need further help.",
        "support_store": "Apple or Google handles purchases, refunds, and subscription cancellation through the relevant store account.",
        "operator": "Operator", "address": "Location", "contact": "Contact", "updated": "Updated September 25, 2026",
        "trial_notice": "The 14-day in-app experience begins after a guardian confirms the privacy notice. It does not require a payment method, does not renew automatically, and is not an App Store or Google Play free trial.",
    },
    "de": {
        "lang": "de", "label": "Deutsch", "nav": ["Datenschutz", "Nutzungsbedingungen", "Datenschutz für Kinder", "Hilfe"],
        "language_label": "Sprache",
        "home_title": "Gute Gewohnheiten, mit Bedacht", "home_lead": "Hier finden Familien die Datenschutzhinweise, Nutzungsbedingungen, Informationen zum Schutz von Kindern und Hilfe zu Yido. Yido Kids speichert Familienaktivitäten standardmäßig auf dem Gerät und verwendet weder personalisierte Werbung noch Analyse-SDKs Dritter.",
        "cards": ["Welche Daten Yido verarbeitet und wo sie gespeichert werden.", "Bedingungen für die Nutzung von Yido durch Familien.", "Elternkontrollen und besonderer Schutz für Kinderdaten.", "Hilfe zur App, zu Käufen und zu Datenschutzanfragen."],
        "support_intro": "Für Hilfe zur App, zu Käufen, zum Datenschutz oder zu Kinderdaten schreiben Sie Yido vertraulich per E-Mail. Senden Sie keine Fotos oder Aufnahmen eines Kindes, sofern wir sie nicht für ein konkretes Anliegen benötigen.",
        "support_private": "Vertrauliche Datenschutz- und Kinderdatenanfragen", "support_public": "Produkthilfe",
        "support_data_heading": "Daten und Löschung", "support_store_heading": "Käufe im Store", "contact_heading": "Betreiber und Kontakt",
        "support_tips": "Prüfen Sie zuerst die Berechtigungen und die Einstellungen für Erinnerungen und Backups. Nennen Sie App-Version, Gerätemodell und Schritte zur Reproduktion, aber keine Inhalte von Kindern.",
        "support_data": "Eltern können Profile, Aufgaben, Check-ins, Fotos und Aufnahmen in der App bearbeiten oder löschen. Eine Deinstallation entfernt lokale App-Daten; System-Backups verwalten Sie in den Geräteeinstellungen. Bei weiteren Fragen schreiben Sie uns eine E-Mail.",
        "support_store": "Käufe, Erstattungen und Kündigungen von Abonnements werden über das jeweilige Konto bei Apple oder Google abgewickelt.",
        "operator": "Betreiber", "address": "Standort", "contact": "Kontakt", "updated": "Aktualisiert am 25. September 2026",
        "trial_notice": "Die 14-tägige App-interne Kennenlernphase beginnt nach Bestätigung des Datenschutzhinweises durch eine sorgeberechtigte Person. Sie erfordert keine Zahlungsmethode, verlängert sich nicht automatisch und ist kein kostenloser Testzeitraum im App Store oder bei Google Play.",
    },
    "es": {
        "lang": "es", "label": "Español", "nav": ["Privacidad", "Condiciones", "Privacidad infantil", "Ayuda"],
        "language_label": "Idioma",
        "home_title": "Buenos hábitos, con cuidado", "home_lead": "Aquí encontrarás la política de privacidad, las condiciones de uso, la información sobre la privacidad infantil y la ayuda de Yido. Yido Kids guarda la actividad familiar en el dispositivo de forma predeterminada y no usa publicidad personalizada ni SDK de análisis de terceros.",
        "cards": ["Qué información trata Yido y dónde se guarda.", "Condiciones para las familias que usan Yido.", "Controles parentales y protección adicional de los datos infantiles.", "Ayuda con la aplicación, las compras y las solicitudes de privacidad."],
        "support_intro": "Para ayuda con la aplicación, compras, privacidad o datos infantiles, escribe a Yido por correo privado. No envíes fotos o grabaciones de menores salvo que te las pidamos para resolver una solicitud concreta.",
        "support_private": "Solicitudes privadas de privacidad y datos infantiles", "support_public": "Ayuda con el producto",
        "support_data_heading": "Datos y eliminación", "support_store_heading": "Compras en la tienda", "contact_heading": "Responsable y contacto",
        "support_tips": "Comprueba los permisos y los ajustes de recordatorios y copias de seguridad. Indica la versión de la aplicación, el modelo del dispositivo y los pasos para reproducir el problema, sin contenido de menores.",
        "support_data": "Los padres pueden editar o borrar perfiles, tareas, registros, fotos y grabaciones en la aplicación. Al desinstalarla se borran los datos locales; las copias del sistema se gestionan en sus ajustes. Si necesitas más ayuda, escríbenos.",
        "support_store": "Apple o Google gestionan las compras, los reembolsos y la cancelación de suscripciones desde la cuenta de la tienda correspondiente.",
        "operator": "Responsable", "address": "Ubicación", "contact": "Contacto", "updated": "Actualizado el 25 de septiembre de 2026",
        "trial_notice": "La experiencia completa de 14 días en la aplicación comienza cuando un tutor confirma el aviso de privacidad. No requiere método de pago, no se renueva automáticamente y no es una prueba gratuita del App Store ni de Google Play.",
    },
    "es-419": {
        "lang": "es-419", "label": "Español (Latinoamérica)", "nav": ["Privacidad", "Términos", "Privacidad infantil", "Ayuda"],
        "language_label": "Idioma",
        "home_title": "Buenos hábitos, con cuidado", "home_lead": "Aquí encontrarás la política de privacidad, los términos de uso, la información sobre privacidad infantil y la ayuda de Yido. Yido Kids guarda la actividad familiar en el dispositivo por defecto y no usa publicidad personalizada ni SDK de análisis de terceros.",
        "cards": ["Qué información maneja Yido y dónde se guarda.", "Términos para las familias que usan Yido.", "Controles parentales y protección adicional de datos infantiles.", "Ayuda con la app, las compras y las solicitudes de privacidad."],
        "support_intro": "Para ayuda con la app, compras, privacidad o datos de niñas y niños, escribe a Yido por correo privado. No envíes fotos o grabaciones infantiles a menos que se soliciten para resolver un caso específico.",
        "support_private": "Solicitudes privadas de privacidad y datos infantiles", "support_public": "Ayuda con la app",
        "support_data_heading": "Datos y eliminación", "support_store_heading": "Compras en la tienda", "contact_heading": "Responsable y contacto",
        "support_tips": "Revisa los permisos y la configuración de recordatorios y respaldos. Indica la versión de la app, el modelo del dispositivo y los pasos para repetir el problema, sin compartir contenido infantil.",
        "support_data": "Madres, padres o tutores pueden editar o borrar perfiles, tareas, registros, fotos y grabaciones en la app. Al desinstalarla se borran los datos locales; los respaldos del sistema se administran en sus ajustes. Si necesitas ayuda, escríbenos.",
        "support_store": "Apple o Google gestionan compras, reembolsos y cancelaciones de suscripciones desde la cuenta de la tienda correspondiente.",
        "operator": "Responsable", "address": "Ubicación", "contact": "Contacto", "updated": "Actualizado el 25 de septiembre de 2026",
        "trial_notice": "La experiencia completa de 14 días en la app comienza cuando un tutor confirma el aviso de privacidad. No requiere medio de pago, no se renueva automáticamente y no es una prueba gratis de App Store ni de Google Play.",
    },
    "fr": {
        "lang": "fr", "label": "Français", "nav": ["Confidentialité", "Conditions d’utilisation", "Vie privée des enfants", "Aide"],
        "language_label": "Langue",
        "home_title": "De bonnes habitudes, en toute attention", "home_lead": "Retrouvez ici la politique de confidentialité, les conditions d’utilisation, la protection des données des enfants et l’aide de Yido. Yido Kids conserve par défaut les activités familiales sur l’appareil et n’utilise ni publicité ciblée ni SDK d’analyse tiers.",
        "cards": ["Les données traitées par Yido et leur stockage.", "Les conditions d’utilisation de Yido en famille.", "Le contrôle parental et la protection des données des enfants.", "L’aide pour l’application, les achats et les demandes relatives à la vie privée."],
        "support_intro": "Pour toute aide concernant l’application, les achats, la confidentialité ou les données d’un enfant, écrivez à Yido en privé par e-mail. N’envoyez pas de photos ou d’enregistrements d’un enfant sans demande précise de notre part.",
        "support_private": "Demandes privées sur la confidentialité et les données des enfants", "support_public": "Aide sur le produit",
        "support_data_heading": "Données et suppression", "support_store_heading": "Achats en boutique", "contact_heading": "Responsable et contact",
        "support_tips": "Vérifiez d’abord les autorisations et les réglages des rappels et sauvegardes. Indiquez la version de l’application, le modèle de l’appareil et les étapes du problème, sans contenu relatif à l’enfant.",
        "support_data": "Les parents peuvent modifier ou supprimer les profils, tâches, pointages, photos et enregistrements dans l’application. La désinstallation efface les données locales ; les sauvegardes système se gèrent dans les réglages. Écrivez-nous si vous avez besoin d’aide.",
        "support_store": "Apple ou Google gère les achats, remboursements et résiliations d’abonnement depuis le compte de la boutique concernée.",
        "operator": "Responsable", "address": "Localisation", "contact": "Contact", "updated": "Mis à jour le 25 septembre 2026",
        "trial_notice": "La période de découverte de 14 jours dans l’application commence après validation de l’avis de confidentialité par un responsable légal. Elle ne demande aucun moyen de paiement, ne se renouvelle pas automatiquement et ne constitue pas un essai gratuit de l’App Store ou de Google Play.",
    },
    "hi": {
        "lang": "hi", "label": "हिन्दी", "nav": ["गोपनीयता", "उपयोग की शर्तें", "बच्चों की गोपनीयता", "सहायता"],
        "language_label": "भाषा",
        "home_title": "अच्छी आदतें, पूरी सावधानी से", "home_lead": "Yido की गोपनीयता नीति, उपयोग की शर्तें, बच्चों की गोपनीयता और सहायता यहाँ उपलब्ध हैं। Yido Kids परिवार की गतिविधि सामान्यतः डिवाइस पर रखता है और लक्षित विज्ञापन या तीसरे पक्ष के एनालिटिक्स SDK का उपयोग नहीं करता।",
        "cards": ["Yido कौन-सी जानकारी संभालता है और कहाँ रखता है।", "Yido इस्तेमाल करने वाले परिवारों के लिए शर्तें।", "अभिभावक नियंत्रण और बच्चों के डेटा की अतिरिक्त सुरक्षा।", "ऐप, खरीद और गोपनीयता अनुरोधों में सहायता।"],
        "support_intro": "ऐप, खरीद, गोपनीयता या बच्चों के डेटा के बारे में सहायता के लिए Yido को निजी ईमेल भेजें। किसी विशेष अनुरोध के लिए हम न कहें तो बच्चे की फ़ोटो या रिकॉर्डिंग न भेजें।",
        "support_private": "गोपनीयता और बच्चों के डेटा के लिए निजी अनुरोध", "support_public": "ऐप सहायता",
        "support_data_heading": "डेटा और हटाना", "support_store_heading": "स्टोर से खरीद", "contact_heading": "संचालक और संपर्क",
        "support_tips": "पहले ऐप की अनुमतियाँ और रिमाइंडर व बैकअप सेटिंग जाँचें। ऐप संस्करण, डिवाइस मॉडल और समस्या दोहराने के चरण बताएं, लेकिन बच्चे की सामग्री न भेजें।",
        "support_data": "अभिभावक ऐप में प्रोफ़ाइल, कार्य, चेक-इन, फ़ोटो और रिकॉर्डिंग बदल या मिटा सकते हैं। ऐप हटाने से स्थानीय डेटा मिटता है; सिस्टम बैकअप सेटिंग में प्रबंधित करें। अधिक सहायता के लिए ईमेल करें।",
        "support_store": "खरीद, रिफंड और सदस्यता रद्द करने की प्रक्रिया संबंधित Apple या Google स्टोर खाते से होती है।",
        "operator": "संचालक", "address": "स्थान", "contact": "संपर्क", "updated": "अपडेट: 25 सितंबर 2026",
        "trial_notice": "अभिभावक द्वारा गोपनीयता सूचना की पुष्टि के बाद ऐप में 14 दिनों का पूरा अनुभव शुरू होता है। इसके लिए भुगतान विधि नहीं चाहिए, यह अपने आप नवीनीकृत नहीं होता और यह App Store या Google Play की मुफ़्त परीक्षण अवधि नहीं है।",
    },
    "ja": {
        "lang": "ja", "label": "日本語", "nav": ["プライバシー", "利用規約", "子どものプライバシー", "サポート"],
        "language_label": "言語",
        "home_title": "安心して、よい習慣を", "home_lead": "Yido のプライバシーポリシー、利用規約、子どもの個人情報保護、サポートをまとめています。Yido Kids は家族の利用データを原則として端末内に保存し、行動ターゲティング広告や第三者の分析 SDK を使用しません。",
        "cards": ["Yido が扱う情報と保存先。", "家族で Yido を使う際の基本的な約束。", "保護者による管理と子どもの情報の保護。", "アプリ、購入、プライバシーに関するお問い合わせ。"],
        "support_intro": "アプリ、購入、プライバシー、子どもの情報に関するご相談は、Yido に非公開のメールでご連絡ください。個別の対応で依頼する場合を除き、子どもの写真や録音を送らないでください。",
        "support_private": "プライバシー・子どもの情報に関する非公開の窓口", "support_public": "製品サポート",
        "support_data_heading": "データと削除", "support_store_heading": "ストアでの購入", "contact_heading": "運営者と連絡先",
        "support_tips": "まず権限と通知・バックアップ設定を確認してください。アプリのバージョン、端末の機種、再現手順を記載し、子どもの情報は添付しないでください。",
        "support_data": "保護者はアプリ内でプロフィール、タスク、チェックイン、写真、録音を編集・削除できます。アプリの削除で端末内データは消去され、OS のバックアップはシステム設定で管理します。必要な場合はメールでご相談ください。",
        "support_store": "購入、返金、定期購入の解約は、該当する Apple または Google のストアアカウントで手続きします。",
        "operator": "運営者", "address": "所在地", "contact": "連絡先", "updated": "更新日：2026年9月25日",
        "trial_notice": "アプリ内の14日間の全機能体験は、保護者がプライバシー通知を確認した後に始まります。支払い方法の登録は不要で、自動更新もされません。App Store または Google Play の無料トライアルではありません。",
    },
    "ko": {
        "lang": "ko", "label": "한국어", "nav": ["개인정보", "이용약관", "아동 개인정보", "지원"],
        "language_label": "언어",
        "home_title": "안심하고 좋은 습관을", "home_lead": "Yido의 개인정보 처리방침, 이용약관, 아동 개인정보 안내 및 지원 정보를 확인할 수 있습니다. Yido Kids는 가족의 활동을 기본적으로 기기에 저장하며 맞춤형 광고나 제3자 분석 SDK를 사용하지 않습니다.",
        "cards": ["Yido가 처리하는 정보와 저장 위치.", "가족의 Yido 이용에 적용되는 조건.", "보호자 관리와 아동 정보의 추가 보호.", "앱, 구매 및 개인정보 요청에 대한 도움."],
        "support_intro": "앱, 구매, 개인정보 또는 아동 데이터에 관한 도움이 필요하면 Yido에 비공개 이메일을 보내 주세요. 특정 요청을 해결하기 위해 별도로 요청하지 않는 한 아동의 사진이나 녹음을 보내지 마세요.",
        "support_private": "개인정보 및 아동 데이터 비공개 요청", "support_public": "제품 지원",
        "support_data_heading": "데이터와 삭제", "support_store_heading": "스토어 구매", "contact_heading": "운영자 및 연락처",
        "support_tips": "먼저 권한과 알림·백업 설정을 확인하세요. 앱 버전, 기기 모델, 재현 단계를 알려 주되 아동의 콘텐츠는 첨부하지 마세요.",
        "support_data": "보호자는 앱에서 프로필, 할 일, 체크인, 사진 및 녹음을 수정하거나 삭제할 수 있습니다. 앱을 제거하면 기기의 로컬 데이터가 삭제되며 OS 백업은 시스템 설정에서 관리합니다. 추가 도움이 필요하면 이메일을 보내 주세요.",
        "support_store": "구매, 환불, 구독 해지는 해당 Apple 또는 Google 스토어 계정에서 처리합니다.",
        "operator": "운영자", "address": "소재지", "contact": "연락처", "updated": "최종 업데이트: 2026년 9월 25일",
        "trial_notice": "앱 내 14일 전체 기능 체험은 보호자가 개인정보 안내를 확인한 뒤 시작됩니다. 결제 수단이 필요 없고 자동 갱신되지 않으며 App Store 또는 Google Play의 무료 체험이 아닙니다.",
    },
    "pt": {
        "lang": "pt-PT", "label": "Português", "nav": ["Privacidade", "Termos", "Privacidade das crianças", "Ajuda"],
        "language_label": "Idioma",
        "home_title": "Bons hábitos, com cuidado", "home_lead": "Encontre aqui a política de privacidade, os termos, a informação sobre a privacidade das crianças e a ajuda do Yido. O Yido Kids guarda a atividade da família no dispositivo por predefinição e não usa publicidade direcionada nem SDKs de análise de terceiros.",
        "cards": ["Que dados o Yido trata e onde são guardados.", "Termos de utilização para as famílias.", "Controlo parental e proteção adicional dos dados das crianças.", "Ajuda com a aplicação, compras e pedidos de privacidade."],
        "support_intro": "Para ajuda com a aplicação, compras, privacidade ou dados de crianças, contacte o Yido por email privado. Não envie fotografias ou gravações de uma criança sem um pedido nosso para resolver uma situação concreta.",
        "support_private": "Pedidos privados sobre privacidade e dados de crianças", "support_public": "Ajuda com o produto",
        "support_data_heading": "Dados e eliminação", "support_store_heading": "Compras na loja", "contact_heading": "Responsável e contacto",
        "support_tips": "Verifique primeiro as permissões e as definições de lembretes e cópias de segurança. Indique a versão da aplicação, o modelo do dispositivo e os passos para reproduzir o problema, sem conteúdo da criança.",
        "support_data": "Os pais podem editar ou apagar perfis, tarefas, registos, fotografias e gravações na aplicação. A desinstalação remove os dados locais; as cópias do sistema são geridas nas definições. Envie-nos um email se precisar de ajuda.",
        "support_store": "A Apple ou a Google trata das compras, dos reembolsos e do cancelamento de subscrições na respetiva conta da loja.",
        "operator": "Responsável", "address": "Localização", "contact": "Contacto", "updated": "Atualizado em 25 de setembro de 2026",
        "trial_notice": "A experiência completa de 14 dias na aplicação começa após a confirmação do aviso de privacidade por um responsável. Não requer método de pagamento, não renova automaticamente e não é um período experimental gratuito da App Store ou da Google Play.",
    },
    "pt-BR": {
        "lang": "pt-BR", "label": "Português (Brasil)", "nav": ["Privacidade", "Termos", "Privacidade infantil", "Ajuda"],
        "language_label": "Idioma",
        "home_title": "Bons hábitos, com cuidado", "home_lead": "Encontre aqui a política de privacidade, os termos, as informações sobre privacidade infantil e a ajuda do Yido. O Yido Kids guarda a atividade da família no dispositivo por padrão e não usa publicidade direcionada nem SDKs de análise de terceiros.",
        "cards": ["Quais dados o Yido trata e onde ficam armazenados.", "Termos de uso para famílias.", "Controles parentais e proteção adicional dos dados das crianças.", "Ajuda com o aplicativo, compras e solicitações de privacidade."],
        "support_intro": "Para ajuda com o aplicativo, compras, privacidade ou dados de crianças, entre em contato com o Yido por e-mail privado. Não envie fotos ou gravações de uma criança sem uma solicitação específica nossa.",
        "support_private": "Solicitações privadas sobre privacidade e dados de crianças", "support_public": "Ajuda com o aplicativo",
        "support_data_heading": "Dados e exclusão", "support_store_heading": "Compras na loja", "contact_heading": "Responsável e contato",
        "support_tips": "Confira primeiro as permissões e as configurações de lembretes e backup. Informe a versão do aplicativo, o modelo do dispositivo e as etapas para reproduzir o problema, sem conteúdo da criança.",
        "support_data": "Responsáveis podem editar ou excluir perfis, tarefas, registros, fotos e gravações no aplicativo. A desinstalação remove os dados locais; backups do sistema são gerenciados nas configurações. Envie um e-mail se precisar de ajuda.",
        "support_store": "Apple ou Google gerencia compras, reembolsos e cancelamentos de assinaturas na conta da loja correspondente.",
        "operator": "Responsável", "address": "Localização", "contact": "Contato", "updated": "Atualizado em 25 de setembro de 2026",
        "trial_notice": "A experiência completa de 14 dias no aplicativo começa depois que um responsável confirma o aviso de privacidade. Não exige forma de pagamento, não renova automaticamente e não é um teste grátis da App Store ou do Google Play.",
    },
    "zh": {
        "lang": "zh-CN", "label": "简体中文", "nav": ["隐私政策", "用户协议", "儿童隐私", "支持"],
        "language_label": "语言",
        "home_title": "安心养成好习惯", "home_lead": "这里集中提供 Yido 的隐私政策、用户协议、儿童个人信息保护说明与支持入口。Yido Kids 默认将家庭活动数据保存在本机，不投放定向广告，也不使用第三方统计 SDK。",
        "cards": ["了解 Yido 处理哪些信息，以及数据存放在哪里。", "家庭使用 Yido 时适用的基本条款。", "家长控制与儿童信息的额外保护。", "应用、购买及隐私请求的帮助入口。"],
        "support_intro": "应用使用、购买、隐私或儿童信息相关问题，请通过电子邮件私下联系 Yido。除非我们为处理具体请求而明确提出，请不要发送儿童照片或录音。",
        "support_private": "隐私与儿童信息的私密联系渠道", "support_public": "产品帮助",
        "support_data_heading": "数据管理与删除", "support_store_heading": "商店购买", "contact_heading": "运营者与联系方式",
        "support_tips": "反馈前可先检查系统权限，以及 Yido 的提醒和备份设置。请提供应用版本、设备型号和复现步骤，但不要附上儿童内容。",
        "support_data": "家长可在应用内编辑或删除档案、任务、打卡、照片和录音。卸载应用会删除本机数据；系统备份需在系统设置中管理。如需进一步帮助，请发邮件联系我们。",
        "support_store": "购买、退款和取消订阅由 Apple 或 Google 商店处理，请在对应商店账户中操作。",
        "operator": "运营者", "address": "所在地", "contact": "联系邮箱", "updated": "更新日期：2026 年 9 月 25 日",
        "trial_notice": "监护人确认隐私提示后，应用内 14 天完整体验开始。无需绑定支付方式，不会自动续订，也不是 App Store 或 Google Play 的商店免费试用。",
    },
    "zh-Hant": {
        "lang": "zh-Hant", "label": "繁體中文", "nav": ["隱私權政策", "使用條款", "兒童隱私", "支援"],
        "language_label": "語言",
        "home_title": "安心養成好習慣", "home_lead": "這裡集中提供 Yido 的隱私權政策、使用條款、兒童個人資料保護說明與支援資訊。Yido Kids 預設將家庭活動資料儲存在裝置上，不投放定向廣告，也不使用第三方分析 SDK。",
        "cards": ["了解 Yido 處理哪些資料，以及資料儲存的位置。", "家庭使用 Yido 時適用的基本條款。", "家長控制與兒童資料的額外保護。", "應用程式、購買及隱私請求的協助管道。"],
        "support_intro": "應用程式使用、購買、隱私或兒童資料相關問題，請透過電子郵件私下聯絡 Yido。除非我們為處理具體請求而明確提出，請不要寄送兒童相片或錄音。",
        "support_private": "隱私與兒童資料的私密聯絡管道", "support_public": "產品協助",
        "support_data_heading": "資料管理與刪除", "support_store_heading": "商店購買", "contact_heading": "營運者與聯絡方式",
        "support_tips": "回報前可先檢查系統權限，以及 Yido 的提醒和備份設定。請提供應用程式版本、裝置型號與重現步驟，但不要附上兒童內容。",
        "support_data": "家長可在應用程式中編輯或刪除個人檔案、任務、打卡、相片和錄音。解除安裝會刪除裝置上的資料；系統備份需在系統設定中管理。如需進一步協助，請寄信給我們。",
        "support_store": "購買、退款和取消訂閱由 Apple 或 Google 商店處理，請在對應商店帳戶中操作。",
        "operator": "營運者", "address": "所在地", "contact": "聯絡信箱", "updated": "更新日期：2026 年 9 月 25 日",
        "trial_notice": "監護人確認隱私提示後，應用程式內的 14 天完整體驗開始。無需綁定付款方式，不會自動續訂，也不是 App Store 或 Google Play 的商店免費試用。",
    },
}

ORDER = ("en", "de", "es", "es-419", "fr", "hi", "ja", "ko", "pt", "pt-BR", "zh", "zh-Hant")
